### PR TITLE
Add reset

### PR DESCRIPTION
**Pull request by HenrikJoreteg**
Continuation of #11

### CODE REVIEW

**Comment by bear** [comment]
@nickryall did you make the change that @HenrikJoreteg requested?

**Comment by nickryall** [comment]
@bear @HenrikJoreteg Before we can remove the skipValidation flag in the formView clear method we would need to make the clear methods in inputView and selectView not trigger validation by default. I'm happy to make these changes to each repo. What do you think?

**Comment by wraithgar** [comment]
Looks like that got made, is this ready to go?  select-view doesn't have a reset yet but that could be something we need to do next, right?

**Comment by nickryall** [comment]
Select view has a clear method pending in this PR https://github.com/AmpersandJS/ampersand-select-view/pull/15. 

But this is ready go without that.

**Comment by kamilogorek** [comment]
I'm not sure about altering `this.each` as an fields operator. I'd rather stick with `this._fieldViewsArray.forEach` in both places so it's easier to reason about.
Plus there has been `clear` method added, but it's not documented as well as it doesn't have test coverage.

**Comment by nickryall** [comment]
I'd be happy to make any changes as well as write tests and documentation. 

I'm not sure about the clear method in the latest commit though. What was the 'resetValidation' argument added in for? @HenrikJoreteg Was that an alternative implementation of 'skipValidation' that should now be removed?

**Comment by nickryall** [comment]
I've made these updates on my fork, although I'm unsure the best way to merge it into here if we wanted to use it:

https://github.com/nickryall/ampersand-form-view/commit/636216627aec13044dab673c4538ee0274dd1021

Changes made are:

1. Remove the 'resetValidation' argument from the 'clear' method.
2. Use `this._fieldViewsArray.forEach` in both `clear` and `reset` methods. Remove `this.each` utility method.
3. Add documentation and tests for `clear` method.
4. Modified `reset` method tests for clarity. i.e. Set an initial value on the fields and reset to that.
5. Don't append the test input fields to document.body so that the Tape output can be viewed in a browser.

**Comment by wraithgar** [comment]
@nickryall I merged them in here

**Comment by wraithgar** [comment]
This looks good now

**Comment by kamilogorek** [comment]
Thanks! +1

**Comment by wraithgar** [comment]
Merged. Minor?

**Comment by kamilogorek** [comment]
@wraithgar looks like that.

**Comment by wraithgar** [comment]
v2.3.0

**Pull request merged**
