### PR TITLE
Update ampersand-view to version 9

### PR DESCRIPTION
**Pull request by imorrison**
Also, updates dev dependencies that now required version 9 as well.

### CODE REVIEW

**Comment by achingbrain** [comment]
This is a duplicate of #61

**Comment by imorrison** [comment]
durp.

**Comment by wraithgar** [comment]
Still appreciate the effort @imorrison!  Thanks!

**Comment by achingbrain** [comment]
Absolutely, great work!

**Comment by imorrison** [comment]
No problem! 
opensource

**Pull request closed without merging**
