### PR TITLE
Dhritzkiv extend clean

### PR DESCRIPTION
**Pull request by wraithgar**
Merge-conflict-free version of https://github.com/AmpersandJS/ampersand-form-view/pull/33

### CODE REVIEW

**Comment by kamilogorek** [comment]
:+1:

**Comment by wraithgar** [comment]
This had a +1 from me in his original PR.

**Comment by wraithgar** [comment]
Minor, since this is new functionality.

**Comment by wraithgar** [comment]
Published as v2.4.0

**Pull request merged**
