### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by dhritzkiv**
This will now update ampersand-form-view to use lodash v4

### CODE REVIEW

**Comment by cdaringe** [comment]
+1

**Comment by wraithgar** [comment]
Will publish after testing locally and push major as per the pattern we established w/ the other modules moving to lodash4

**Comment by wraithgar** [comment]
published as `v7.0.0`

**Comment by dhritzkiv** [comment]
Great! There's at least two more libraries –ampersand-checkbox-view and ampersand-select-view– that I didn't get to this weekend. Working on updating them now.

**Comment by wraithgar** [comment]
Thank you so much for doing this gardening!

**Pull request merged**
