### PR TITLE
"Tests"

### PR DESCRIPTION
**Pull request by mrDarcyMurphy**
What I'd like to do is refactor `ampersand-form-view` so that it properly extends `ampersand-view`. Before I do that though, I figured it'd be best to get some tests in place, so this is the *bare minimum* necessary to say that it's "tested." My philosophy was:

1. To change *nothing* in the code, that way a release isn't necessary.
2. To base the test config and patterns on `ampersand-view` for forward compatibility.

In doing that though, I found:

- The suite runs in PhantomJS.
- PhantomJS 2.0 doesn't run on a mac.
- PhantomJS 1.9.8 still doesn't support `Function.prototype.bind`.
- The form view is using bind in a few places. ([L33](https://github.com/AmpersandJS/ampersand-form-view/blob/master/ampersand-form-view.js#L33), 
[L40](https://github.com/AmpersandJS/ampersand-form-view/blob/master/ampersand-form-view.js#L40), 
[L144](https://github.com/AmpersandJS/ampersand-form-view/blob/master/ampersand-form-view.js#L144))

So I added a polyfill for bind to the tests, which defeats the purpose of testing but given that the whole thing is likely to change I figured this was the lesser of two evils and doesn't violate point 1.

A few more points:

- I'd like to add more tests but haven't been able to make the time, so I'm hoping that by getting a suite in place then I, and anyone else, can add a test here and there until the essential things that make `ampersand-form-view` what it is are covered, then conversion to an `ampersand-view` can begin.
- I'm totally cool with this PR being rejected. At the very least I'd like to start a discussion to see what the core team thinks of approaching a refactor iteratively.

### CODE REVIEW

**Comment by chesles** [comment]
@mrDarcyMurphy I had the same line of thought - based on the fact that there are 2-3 individual issues already about converting `ampersand-form-view` to extend `ampersand-view`, and an [entry on the trello roadmap](https://trello.com/c/KK0ANiEi/43-convert-form-view-to-be-based-on-proper-ampersand-view), I think it will happen eventually. A good test suite is a good idea in any case, especially before refactoring.

I didn't see this PR until just now - I started separately on a few tests already over here: https://github.com/chesles/ampersand-form-view/compare/tests

**Comment by mrDarcyMurphy** [comment]
@chesles Cool. Might be worth combining our efforts on this. How would you like to do that?

**Comment by chesles** [comment]
@mrDarcyMurphy Sure thing! I can add you as a collaborator on my fork so you can push to it. Then we can make a new PR from there and close this one. I think that should work?

**Comment by mrDarcyMurphy** [comment]
Sounds good to me. I'll close this for now and help out on your branch when I can.

**Comment by wraithgar** [comment]
Heads up there were tests added in this PR https://github.com/AmpersandJS/ampersand-form-view/pull/19

**Comment by chesles** [comment]
Thanks for the heads up @wraithgar - looks like not much has been duplicated there in terms of the tests themselves, so I'll rebase my branch on master now that that's merged.

@mrDarcyMurphy heads up if you've pulled my branch already, I'm going to rebase and force push. You'll probably want to delete and pull again if you have.

**Comment by chesles** [comment]
New PR: #30

**Pull request closed without merging**
